adevis_app_comment:
    resource: "@MikyCommentBundle/Resources/config/routing/frontend.yml"
    prefix : /comment

adevis_admin_comment:
    resource: "@MikyCommentBundle/Resources/config/routing/backend.yml"
    prefix : /%admin_prefix_path%