#miky_app_comment:
#    resource: "@MikyCommentBundle/Resources/config/routing/frontend.yml"
#    prefix : /comment
#
#miky_admin_comment:
#    resource: "@MikyCommentBundle/Resources/config/routing/backend.yml"
#    prefix : /%miky_admin.admin_path%
#