miky_resource:
    resources:
        miky.comment:
            classes:
                model: %comment.entity.class%
            contexts:
                admin: ~

miky_grid:
    grids:
        miky_comment_admin:
            driver:
                options:
                    class: %comment.entity.class%
            sorting:
                createdAt:
                    path: createdAt
                    direction: desc
            fields:
                id:
                    type: string
                    label: miky.ui.id
                body:
                    type: string
                    label: miky.ui.content
            filters:
                body:
                    type: string
                    label: miky.ui.content

            actions:
                item:
                    update:
                        type: update
                    delete:
                        type: delete
