miky_admin_comment:
    resource: |
        alias: miky.comment
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        form: miky_comment_admin
        grid: miky_comment_admin
        permission: true
        vars:
            all:
                subheader: miky.ui.manage_comments
            index:
                icon: bookmark-o
    type: miky.resource


