miky_app_comment_user_list:
    path:      /user/list
    defaults:  { _controller: MikyCommentBundle:Frontend/UserComment:list}

miky_app_comment_user_remove:
    path:      /{comment}/remove
    defaults:  { _controller: MikyCommentBundle:Frontend/UserComment:remove}

miky_app_comment_ad_create:
    path:      /{ad}/create
    defaults:  { _controller: MikyCommentBundle:Frontend/UserComment:create}